pipeline {
    agent any

    parameters{
        string(name: 'NAME', defaultValue: 'nextjs')
    }

    tools {
        nodejs "nodejs-20.4.0"
    }

    stages {
        stage('Nextjs build'){
            steps{
                dir('frontend/yoyak-web'){
                    echo 'Nextjs build...'
                    nodejs(nodeJSInstallationName: 'nodejs-20.4.0') {
                        sh 'npm install && npm run build'
                    }
                }
            }
        }
    }
}
