pipeline {
    agent any

    parameters{
        string(name: 'NAME', defaultValue: 'nextjs')
    }

    tools {
        nodejs "nodejs-20.4.0"
    }

    stages {
        stage('Nextjs build'){
            steps{
                dir('frontend/yoyak-web'){
                    echo 'Nextjs build...'
                    sh 'npm install'
                    sh 'CI=false npm run build'
                }
            }
        }
    }
}
